package appconfig.parsers

import appconfig.GRADLE_TASK_NAME
import org.gradle.api.Project

object GoogleMapsApiKeyHandler {

    private const val PATH = "src/main/res/values/google_maps_api_key.xml"


    /**
     * Create strings resource file with Google maps api key
     */
    private val gMapsApiKeyStringsXmlTemplate = """
        <?xml version="1.0" encoding="utf-8"?>
        <!--Do not modify. Generated by '$GRADLE_TASK_NAME' task-->
        <resources>
            <string name="google_maps_api_key" translatable="false">%s</string>
        </resources>
    """.trimIndent()

    fun generateXml(customProject: Project, apiKey: String) {
        print("Generating google maps strings.xml... ")

        val file = customProject.file(PATH)

        if (!file.exists()) {
            file.createNewFile()
        }

        file.writeText(gMapsApiKeyStringsXmlTemplate.format(apiKey))

        println("✅ ")
    }
}