package appconfig.parsers

import appconfig.AdvertisingMode
import appconfig.GRADLE_TASK_NAME
import org.gradle.api.Project

object GoogleAdMobAppIdHandler {

    private const val PATH = "src/main/res/values/appodeal_config.xml"

    private const val GRADLE_PATH = "build.gradle.kts"

    private const val MANIFEST_PATH = "src/main/AndroidManifest.xml"

    private const val ADMOB_FULL_INFO =
        """    <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="@string/google_admob_app_id" />
    </application>"""

    private val ADMOB_FULL_INFO_REGEX =
        """[ ]*<meta-data[ ]*
            [ ]*android:name="com.google.android.gms.ads.APPLICATION_ID"[ ]*
            [ ]*android:value="@string/google_admob_app_id" />[ ]*""".trimIndent().toRegex()

    /**
     * Create strings resource file with Advertising configs
     */
    private val template = """
        <?xml version="1.0" encoding="utf-8"?>
        <!--Do not modify. Generated by '$GRADLE_TASK_NAME' task-->
        <resources>
            <string name="google_admob_app_id" translatable="false">%s</string>
        </resources>
    """.trimIndent()

    fun handleAdmobConfig(
        project: Project,
        appModule: Project,
        advertising: com.google.gson.JsonObject?,
        googleAdmobAppId: String,
        isAppodealKeyEmpty: Boolean
    ) {
        print("Generating advertising config strings.xml... ")

        // Migration comes first: it can stop the task, and a partial generation is harder to
        // recover from than a refusal to start
        migrateOldSubstitution(appModule)


        handleManifest(
            module = appModule,
            googleAdmobIsEmpty = googleAdmobAppId.isBlank(),
            isAppodealKeyEmpty = isAppodealKeyEmpty
        )

        val appodealConfig = appModule.file(PATH)

        if (!appodealConfig.exists()) {
            appodealConfig.createNewFile()
        }

        appodealConfig.writeText(
            template.format(googleAdmobAppId)
        )

        println("✅ ")
    }

    /**
     * Writes the advertising mode and the configuration fingerprint into
     * advertising.properties. Nothing in the sources is searched for or
     * substituted: the dependency list lives in app/build.gradle.kts under a
     * when, and the mode only records which branch the configuration implies.
     */
    fun writeAdvertisingProperties(
        project: Project,
        advertising: com.google.gson.JsonObject?,
        googleAdmobAppId: String,
        isAppodealKeyEmpty: Boolean
    ) {
        val mode = AdvertisingMode.modeOf(
            appodealApiKey = if (isAppodealKeyEmpty) null else "set",
            googleAdmobAppId = googleAdmobAppId.ifBlank { null }
        )
        project.rootProject.file(AdvertisingMode.FILE_NAME)
            .writeText(AdvertisingMode.fileContent(mode, AdvertisingMode.hashOf(advertising)))
        // Say the outcome out loud: a filled google_admob_app_id without an appodeal_api_key
        // yields none, and without this line the partner learns that only from the absence of
        // ads
        println("  advertising mode: $mode")
    }

    /**
     * A one-off migration. A partner who built the app from an earlier template
     * carries the result of the old substitution in app/build.gradle.kts: the
     * line implementation(libs.appodeal.core), or the AdMob block, or a call to
     * appodealNetworkWithoutAdmob(). Dependencies are now declared through a
     * when, so those leftovers have to go or they would declare them twice.
     *
     * To be removed once every partner has updated.
     */
    private fun migrateOldSubstitution(module: Project) {
        val gradleFile = module.file(GRADLE_PATH)
        val text = gradleFile.readText()
        // Only the forms the previous version of the task used to substitute are removed.
        // Nothing else is touched: the partner may have reformatted the declaration or added
        // their own excludes, and a blind regex would leave dangling brackets behind.
        val known = listOf(
            "implementation(libs.appodeal) { exclude(\"com.android.billingclient\", \"billing\") }",
            "implementation(libs.appodeal.core)",
            "appodealNetworkWithoutAdmob()"
        )
        var cleaned = text
        for (form in known) {
            cleaned = cleaned.replace(Regex("\\n[ \\t]*" + Regex.escape(form) + "[ \\t]*(?=\\n)"), "")
        }

        // If Appodeal declarations we do not recognise are left, say so rather than stay
        // silent: the partner has to remove them, otherwise the dependencies are declared twice
        val leftovers = Regex(
            "\\n[ \\t]*(implementation\\(libs\\.appodeal(\\.core)?\\s*[\\)\\{]|appodealNetworkWithoutAdmob\\s*\\()[^\\n]*"
        ).findAll(cleaned).map { it.value.trim() }.toList()
        if (leftovers.isNotEmpty()) {
            throw org.gradle.api.GradleException(
                "app/build.gradle.kts still declares Appodeal in a form this task does not " +
                    "recognise:\n" +
                    leftovers.joinToString("\n") { "  $it" } +
                    "\nThese are leftovers of the previous way of configuring ads. Remove them " +
                    "by hand: the dependencies are now declared by the when block in that same " +
                    "file, chosen from your configuration, and duplicates lead to version " +
                    "conflicts."
            )
        }

        if (cleaned != text) {
            gradleFile.writeText(cleaned)
            println("  removed leftovers of the previous Appodeal dependency substitution")
        }
    }

    private fun handleManifest(
        module: Project,
        googleAdmobIsEmpty: Boolean,
        isAppodealKeyEmpty: Boolean
    ) {
        val manifestFile = module.file(MANIFEST_PATH)
        val manifestFileText = manifestFile.readText()

        if (googleAdmobIsEmpty || isAppodealKeyEmpty) {
            val editedManifestText = manifestFileText.replace(ADMOB_FULL_INFO_REGEX, "")
            manifestFile.writeText(editedManifestText)
        } else {
            if (!manifestFileText.contains(ADMOB_FULL_INFO_REGEX)) {
                val editedManifestText = manifestFileText.replace("</application>", ADMOB_FULL_INFO)
                manifestFile.writeText(editedManifestText)
            }
        }
    }
}