package appconfig.parsers

import appconfig.GRADLE_TASK_NAME
import org.gradle.api.Project

object GoogleAdMobAppIdHandler {

    private const val PATH = "src/main/res/values/appodeal_config.xml"

    private const val GRADLE_PATH = "build.gradle.kts"

    private const val MANIFEST_PATH = "src/main/AndroidManifest.xml"

    private const val APPODEAL_WITH_ADMOB =
        "implementation(libs.appodeal) { exclude(\"com.android.billingclient\", \"billing\") }"

    private const val APPODEAL_CORE = "implementation(libs.appodeal.core)"

    private const val APPODEAL_WITHOUT_ADMOB = """
    implementation(libs.appodeal.core)
    appodealNetworkWithoutAdmob()
    """

    private const val ADMOB_FULL_INFO =
        """    <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="@string/google_admob_app_id" />
    </application>"""

    private val ADMOB_FULL_INFO_REGEX =
        """[ ]*<meta-data[ ]*
            [ ]*android:name="com.google.android.gms.ads.APPLICATION_ID"[ ]*
            [ ]*android:value="@string/google_admob_app_id" />[ ]*""".trimIndent().toRegex()

    /**
     * Create strings resource file with Advertising configs
     */
    private val template = """
        <?xml version="1.0" encoding="utf-8"?>
        <!--Do not modify. Generated by '$GRADLE_TASK_NAME' task-->
        <resources>
            <string name="google_admob_app_id" translatable="false">%s</string>
        </resources>
    """.trimIndent()

    fun handleAdmobConfig(
        appModule: Project,
        googleAdmobAppId: String,
        isAppodealKeyEmpty: Boolean
    ) {
        print("Generating advertising config strings.xml... ")

        handleAppodealGradleDeps(
            module = appModule,
            googleAdmobIsEmpty = googleAdmobAppId.isBlank(),
            isAppodealKeyEmpty = isAppodealKeyEmpty
        )

        handleManifest(
            module = appModule,
            googleAdmobIsEmpty = googleAdmobAppId.isBlank(),
            isAppodealKeyEmpty = isAppodealKeyEmpty
        )

        val appodealConfig = appModule.file(PATH)

        if (!appodealConfig.exists()) {
            appodealConfig.createNewFile()
        }

        appodealConfig.writeText(
            template.format(googleAdmobAppId)
        )

        println("✅ ")
    }

    private fun handleAppodealGradleDeps(
        module: Project,
        googleAdmobIsEmpty: Boolean,
        isAppodealKeyEmpty: Boolean
    ) {
        val gradleFile = module.file(GRADLE_PATH)

        // Сначала приводим объявление к общему виду и только потом применяем
        // нужное. Без этого второй запуск задачи раздувает файл: блок
        // APPODEAL_WITHOUT_ADMOB содержит внутри себя строку APPODEAL_CORE,
        // и замена срабатывает по уже вставленному тексту.
        val normalized = normalizeAppodealDeps(gradleFile.readText())

        val editedGradleText = when {
            isAppodealKeyEmpty -> normalized
            googleAdmobIsEmpty -> normalized.replace(APPODEAL_CORE, APPODEAL_WITHOUT_ADMOB)
            else -> normalized.replace(APPODEAL_CORE, APPODEAL_WITH_ADMOB)
        }

        gradleFile.writeText(editedGradleText)
    }

    /**
     * Возвращает объявление зависимостей Appodeal к базовому виду
     * (одна строка APPODEAL_CORE), сколько бы раз задача ни отрабатывала до
     * этого.
     */
    private fun normalizeAppodealDeps(text: String): String = text
        .replace(APPODEAL_WITH_ADMOB, APPODEAL_CORE)
        .replace(Regex("""\n[ \t]*appodealNetworkWithoutAdmob\(\)"""), "")
        .replace(
            Regex("""(\n[ \t]*implementation\(libs\.appodeal\.core\))+"""),
            "\n    " + APPODEAL_CORE
        )

    private fun handleManifest(
        module: Project,
        googleAdmobIsEmpty: Boolean,
        isAppodealKeyEmpty: Boolean
    ) {
        val manifestFile = module.file(MANIFEST_PATH)
        val manifestFileText = manifestFile.readText()

        if (googleAdmobIsEmpty || isAppodealKeyEmpty) {
            val editedManifestText = manifestFileText.replace(ADMOB_FULL_INFO_REGEX, "")
            manifestFile.writeText(editedManifestText)
        } else {
            if (!manifestFileText.contains(ADMOB_FULL_INFO_REGEX)) {
                val editedManifestText = manifestFileText.replace("</application>", ADMOB_FULL_INFO)
                manifestFile.writeText(editedManifestText)
            }
        }
    }
}