package com.travelapp.config

import com.travelapp.sdk.config.CornerType
import com.travelapp.sdk.config.AppTabs
import com.travelapp.sdk.config.EnabledInfoItems
import com.travelapp.sdk.config.IconsType
        
/**
* Do not modify! Auto generated by 'parseConfig' task
*/
object WhiteLabelConf {
    
    const val apiKey: String = "1357a67c2ab973dc8604f34481e7c51f"

    const val email: String = "test@test.com"

    const val feedbackTheme: String = ""

    const val appVerison: String = "1.5.0"

    const val appId: String = "com.travelapp"

    val reviewRequestFrequency: Int = 0

    val marker: Int = 418761
    
    val clientDeviceHost: String = "iphone.apartments"

    val flightsTabEnabled: Boolean = true

    const val sharingLink: String = "https://travelapp.whitelabel.org"

    const val handlingLink: String = "https://travelapp.whitelabel.org"

    const val appsflyerDevKey: String = ""

    const val appStoreLink: String = ""

    object Style {
        val cornerType: CornerType = CornerType.getByName("round")
        val iconsType: IconsType = IconsType.getByName("tint")
    }
    
    object InfoConfig {
        val enabledItems: Set<EnabledInfoItems> = setOf<EnabledInfoItems?>(
            EnabledInfoItems.getByName("about_app"), EnabledInfoItems.getByName("rate_app"), EnabledInfoItems.getByName("share_app"), EnabledInfoItems.getByName("favorites")
        ).filterNotNull().toSet()
    }

    object Advertising {
        const val appodealApiKey: String = "e17770bc804233f23f7a8fdfd5e8c7f2d0053be8630313a8"

        object Placements {
            const val airTicketPlacementInterstitial: String = "air_ticket_placement_interstitial"

            const val airTicketPlacementBanner: String = "air_ticket_placement_banner"
        }
    }




    
    

    
}