package appconfig

import com.google.gson.Gson
import com.google.gson.JsonElement
import com.google.gson.JsonObject
import com.google.gson.JsonSyntaxException
import org.gradle.api.GradleException
import org.gradle.api.Project
import java.security.MessageDigest

/**
 * The advertising mode, derived from the advertising block of
 * config/app_config.json.
 *
 * Advertising used to be wired up by text substitution: parseConfig looked for
 * the line implementation(libs.appodeal.core) in app/build.gradle.kts and
 * replaced it with the right set of dependencies. When the SDK dependencies
 * moved into the travel-sdk module that line disappeared, the replacement
 * matched nothing, and ads stopped being wired up at all - silently, without a
 * single error.
 *
 * Now nothing is substituted. The dependency list lives in app/build.gradle.kts
 * under a when, and the mode that selects a branch is derived here, from the
 * configuration file. There is nothing to search for, so nothing to break.
 *
 * advertising.properties is not a second source of truth: parseConfig writes the
 * mode there for reference and a fingerprint of the advertising block next to
 * it. The fingerprint answers one question - whether the generated resources
 * (the manifest entry and appodeal_config.xml) still match the configuration
 * they were generated from.
 */
object AdvertisingMode {

    const val NONE = "none"
    const val APPODEAL = "appodeal"
    const val APPODEAL_ADMOB = "appodeal_admob"

    const val FILE_NAME = "advertising.properties"
    private const val VERIFY_TASK_NAME = "verifyAdvertisingWiring"
    private const val KEY_MODE = "adsMode"
    private const val KEY_HASH = "configHash"
    private const val CONFIG_PATH = "config/app_config.json"

    /**
     * The hash of the advertising block as it was when the mode was derived, kept
     * so that the stale-resource guard checks the same snapshot the build was
     * configured from. Set while Gradle configures the project, read when the task
     * graph is ready.
     *
     * Cleared at the start of every read(), and that matters: Gradle reuses the
     * buildSrc classloader between builds of the same daemon, so without the reset
     * this field would still hold the hash from a previous build - and the guard
     * would answer about someone else's configuration. Both directions were
     * observed: a stale green in the daemon, and a "run parseConfig" right after
     * parseConfig had been run in another JVM.
     */
    @Volatile
    private var snapshotHash: String? = null

    /** The mode implied by the configuration. Used both when writing and when checking. */
    fun modeOf(appodealApiKey: String?, googleAdmobAppId: String?): String = when {
        appodealApiKey.isNullOrBlank() -> NONE
        googleAdmobAppId.isNullOrBlank() -> APPODEAL
        else -> APPODEAL_ADMOB
    }

    /**
     * A fingerprint of the advertising block in canonical form: keys are sorted
     * at every level, so reformatting the file or reordering fields in an editor
     * does not count as a change. Gson does not normalise the order itself - it
     * preserves insertion order - so the sorting happens before serialisation.
     */
    fun hashOf(advertising: JsonObject?): String {
        val canonical = canonicalize(advertising ?: JsonObject())
        val digest = MessageDigest.getInstance("SHA-256").digest(canonical.toByteArray())
        return digest.joinToString("") { "%02x".format(it) }
    }

    /** A stable textual form: keys sorted recursively. */
    private fun canonicalize(element: JsonElement): String = when {
        element.isJsonObject -> element.asJsonObject.entrySet()
            .sortedBy { it.key }
            .joinToString(",", "{", "}") { "\"${it.key}\":${canonicalize(it.value)}" }
        element.isJsonArray -> element.asJsonArray
            .joinToString(",", "[", "]") { canonicalize(it) }
        else -> element.toString()
    }

    fun fileContent(mode: String, hash: String): String = """
        # Generated by the $GRADLE_TASK_NAME task. Do not edit by hand.
        #
        # The advertising mode is derived from the advertising block in
        # $CONFIG_PATH, which is the only place that decides which ad libraries
        # enter the build. The value below is written for reference; editing it
        # changes nothing. $KEY_HASH records the state of that block, so the build
        # can tell you when the generated advertising resources are stale.
        $KEY_MODE=$mode
        $KEY_HASH=$hash
    """.trimIndent() + "\n"

    /**
     * An explicit mode override. It exists so we can build the advertising
     * branch without touching the shipped config/app_config.json, where the ad
     * keys stay empty.
     *
     * The override applies both to the dependency selection and to the check;
     * otherwise the parameter would change what the check expects without
     * changing what is actually built.
     */
    fun override(project: Project): String? {
        val value = project.providers.gradleProperty("adsMode").orNull ?: return null
        if (value !in listOf(NONE, APPODEAL, APPODEAL_ADMOB)) {
            throw GradleException(
                "Unknown advertising mode override '$value'. Valid values: $NONE, $APPODEAL, " +
                    "$APPODEAL_ADMOB"
            )
        }
        return value
    }

    /**
     * Checks that cannot be made from the command line.
     *
     * Parsing startParameter.taskNames is useless here: it holds exactly what
     * the user typed, abbreviations and task options included. Guessing which
     * option consumes the next argument does not work either - the boolean
     * --rerun takes none, and skipping an argument for it swallowed the real
     * task name, which opened a way around both guards.
     *
     * So the task graph is asked instead: it holds what will actually run, after
     * abbreviations, options and dependencies have been resolved.
     */
    fun registerGuards(project: Project) {
        val overridden = project.providers.gradleProperty("adsMode").orNull != null
        project.gradle.taskGraph.whenReady(
            object : org.gradle.api.Action<org.gradle.api.execution.TaskExecutionGraph> {
                override fun execute(graph: org.gradle.api.execution.TaskExecutionGraph) {
                    val names = graph.allTasks.map { it.name }.toSet()

                    if (overridden) {
                        val other = names - VERIFY_TASK_NAME
                        if (other.isNotEmpty()) {
                            throw GradleException(
                                "The advertising mode override may only be used with the " +
                                    "$VERIFY_TASK_NAME task, and the task graph also contains: " +
                                    summarize(other) + ". It is a check mode: it substitutes the " +
                                    "mode without touching $CONFIG_PATH, so anything built with it " +
                                    "does not match your configuration. The value can come from " +
                                    "-PadsMode on the command line, from gradle.properties or from " +
                                    "the ORG_GRADLE_PROJECT_adsMode environment variable - check " +
                                    "all three if you did not pass it yourself."
                            )
                        }
                    }

                    // Are the generated resources stale? This is checked here rather than at
                    // configuration time because only the graph shows whether parseConfig will
                    // run. The previous guess - "was it mentioned in the command" - accepted any
                    // subsequence of letters, so ./gradlew aR (the standard abbreviation of
                    // assembleRelease) switched the check off.
                    //
                    // The check applies only when the graph actually builds the app, since that
                    // is what consumes the generated resources. The condition used to be "no
                    // parseConfig in the graph", which rejected help, tasks and clean on a stale
                    // configuration - the partner could not even list the tasks to find out what
                    // to do. Which project a task belongs to is taken from the graph rather than
                    // guessed from its name.
                    val touchesApp = graph.allTasks.any { it.project.path == ":app" }
                    if (GRADLE_TASK_NAME !in names && touchesApp) {
                        val configFile = project.rootProject.file(CONFIG_PATH)
                        if (configFile.exists()) {
                            val props = readProps(project)
                            // The hash of the snapshot the mode was derived from, not of a fresh
                            // read. This guard runs when the task graph is ready, which is long
                            // after the mode was chosen at configuration time: re-reading the file
                            // here compared one snapshot of the configuration against the resources
                            // generated from another. Editing the file inside that window produced
                            // a release APK whose configuration asked for ads while no adapter was
                            // in the build - with this check green.
                            val expected = snapshotHash ?: hashOf(advertisingBlock(configFile.readText()))
                            if (props[KEY_HASH] != expected) {
                                throw GradleException(
                                    "The advertising block in $CONFIG_PATH changed after the last " +
                                        "$GRADLE_TASK_NAME run, so the generated advertising " +
                                        "resources are stale: the manifest entry and " +
                                        "appodeal_config.xml still hold the previous values. Run " +
                                        "./gradlew $GRADLE_TASK_NAME"
                                )
                            }
                        }
                    }

                    if (GRADLE_TASK_NAME in names && names.size > 1) {
                        throw GradleException(
                            "$GRADLE_TASK_NAME cannot share a command with other tasks. It writes " +
                                "app_version.properties and handling_link.properties while it " +
                                "runs, and the build reads both while Gradle configures the " +
                                "project - which happens first, so the build would use the " +
                                "previous values. Nothing orders it before the :app tasks either. " +
                                "The graph also contains: " + summarize(names - GRADLE_TASK_NAME) +
                                ". Run ./gradlew $GRADLE_TASK_NAME on its own, then the rest."
                        )
                    }
                }
            }
        )
    }

    /** The first five names and a counter: a graph can hold some four hundred tasks. */
    private fun summarize(names: Set<String>): String {
        val head = names.sorted().take(5)
        val rest = names.size - head.size
        return head.joinToString(", ") + if (rest > 0) " and $rest more" else ""
    }

    /**
     * The advertising block of the configuration file.
     *
     * Both the type of the block and the types of the keys inside it are checked
     * here, because Gson would otherwise fail on a plain cast: a block written as
     * a string or an array stopped every command - help and IDE sync included -
     * with a ClassCastException that named neither the file nor the field. Such a
     * block still stops the build, which is the point; what changed is that the
     * message says which file and which entry to fix.
     *
     * Every path to the block goes through this function, parseConfig included,
     * so a malformed block is reported the same way wherever it is first read.
     */
    fun advertisingBlock(configText: String): JsonObject? {
        val root = try {
            Gson().fromJson(configText, JsonObject::class.java)
        } catch (e: JsonSyntaxException) {
            throw GradleException(
                "$CONFIG_PATH is not valid JSON, so no setting in it can be read: ${e.message}"
            )
        } ?: return null

        val element = root.get("advertising") ?: return null
        if (element.isJsonNull) return null
        if (!element.isJsonObject) {
            throw GradleException(
                "The advertising entry in $CONFIG_PATH must be an object holding the ad keys, " +
                    "not $element. Leave its keys empty if you do not use ads, or remove the " +
                    "entry entirely."
            )
        }
        return element.asJsonObject
    }

    /**
     * A string field of the configuration. Gson silently coerces numbers and
     * booleans to strings, and "appodeal_api_key": 1 used to switch advertising
     * on with a key that could not work - with every check green. The type is
     * checked explicitly.
     */
    private fun stringField(obj: JsonObject?, name: String, path: String = "advertising"): String? {
        val el = obj?.get(name) ?: return null
        if (el.isJsonNull) return null
        if (!el.isJsonPrimitive || !el.asJsonPrimitive.isString) {
            throw GradleException(
                "$path.$name in $CONFIG_PATH must be a string, not $el. Advertising keys and " +
                    "placement names are written as strings, in quotes."
            )
        }
        return el.asString
    }

    private fun readProps(project: Project): Map<String, String> {
        val file = project.rootProject.file(FILE_NAME)
        if (!file.exists()) return emptyMap()
        return file.readLines()
            .filterNot { it.isBlank() || it.trimStart().startsWith("#") }
            .mapNotNull { line -> line.split("=", limit = 2).takeIf { it.size == 2 } }
            .associate { it[0].trim() to it[1].trim() }
    }

    fun read(project: Project): String {
        // Any hash left from an earlier build of this daemon is not ours - drop it before
        // anything can read it. With an override no snapshot is taken at all, and the guard
        // falls back to reading the file, which is what it should do.
        snapshotHash = null

        // The command-line override wins over the configuration. It is allowed only for the
        // verification task, which the task graph guard enforces.
        override(project)?.let {
            project.logger.lifecycle(
                "WARNING: the advertising mode is overridden to '$it' and your configuration is " +
                    "ignored. This is a check mode, not a way to build a release."
            )
            return it
        }

        // The configuration file is the only source of the mode; without it there is nothing
        // to build.
        val configFile = project.rootProject.file(CONFIG_PATH)
        if (!configFile.exists()) {
            throw GradleException(
                "$CONFIG_PATH not found. It holds every setting of the template: without it " +
                    "neither the app nor $GRADLE_TASK_NAME can run. Restore the file from the " +
                    "delivery."
            )
        }

        // The mode is DERIVED from the configuration rather than read from a file.
        //
        // It used to be read from advertising.properties, which made that file a second source
        // of truth: configHash answered "has the configuration changed since parseConfig", but
        // not "does the mode match this configuration". Editing a single line in the file was
        // enough to get 18 ad adapters with empty keys - and verifyAdvertisingWiring called it
        // fine, because it read the mode from the same place. The original defect could be
        // reproduced by editing a file in the root of the delivery.
        //
        // Now there is one source: config/app_config.json. The properties file only records
        // whether the generated resources still match it.
        val advertising = advertisingBlock(configFile.readText())
        snapshotHash = hashOf(advertising)

        val mode = modeOf(
            appodealApiKey = stringField(advertising, "appodeal_api_key"),
            googleAdmobAppId = stringField(advertising, "google_admob_app_id")
        )
        if (mode != NONE) checkPlacements(project, advertising)
        return mode
    }

    /**
     * The placements, once advertising is on. A placement names the ad slot when
     * the app asks Appodeal to show one. With an empty value that format is never
     * shown: the SDK checks for a non-empty name before showing either the banner
     * or the interstitial. The adapters are still in the build and the ads still
     * load - autocache runs for both types - and every check stays green.
     *
     * A wrong type is an error, the same as for the keys: Gson would coerce 123
     * or true into the strings "123" and "true" and hand them to the SDK as if
     * they were real placement names. An empty value is a warning rather than an
     * error, because leaving out one of the two formats is a legitimate choice.
     */
    private fun checkPlacements(project: Project, advertising: JsonObject?) {
        val element = advertising?.get("placements")
        if (element == null || element.isJsonNull) {
            project.logger.warn(
                "WARNING: advertising.placements is missing in $CONFIG_PATH while the ad keys are " +
                    "filled in. The adapters will be in the build, but no ad will be shown: both " +
                    "formats require a non-empty placement name."
            )
            return
        }
        if (!element.isJsonObject) {
            throw GradleException(
                "advertising.placements in $CONFIG_PATH must be an object holding the placement " +
                    "names, not $element."
            )
        }
        val placements = element.asJsonObject
        for (name in listOf("air_ticket_placement_interstitial", "air_ticket_placement_banner")) {
            val value = stringField(placements, name, path = "advertising.placements")
            if (value.isNullOrBlank()) {
                project.logger.warn(
                    "WARNING: advertising.placements.$name is empty in $CONFIG_PATH while the ad " +
                        "keys are filled in. That format will not be shown at all."
                )
            }
        }
    }
}
