package appconfig.templates

import appconfig.GRADLE_TASK_NAME

val colorsXmlTemplate = """
    <?xml version="1.0" encoding="utf-8"?>
    <!--DO NOT MODIFY THIS FILE! IT IS AUTOGENERATED BY '$GRADLE_TASK_NAME' GRADLE TASK-->
    <resources>
        <color name="primary_light">%s</color>
        <color name="primary_dark">%s</color>
        
        <color name="primary_disable_light">%s</color>
        <color name="primary_disable_dark">%s</color>
        
        <color name="primary_pressed_light">%s</color>
        <color name="primary_pressed_dark">%s</color>
        
        <color name="surface_tint_light">%s</color>
        <color name="surface_tint_dark">%s</color>
    </resources>
""".trimIndent()